version: '3.7'
services:
    app_node1:
        image: gameserver
        hostname: app_node1
        depends_on:
            - redis

    app_node2:
        image: gameserver
        hostname: app_node2
        depends_on:
            - redis

    app_node3:
        image: gameserver
        hostname: app_node3
        depends_on:
            - redis

    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - redisData:/data



    nginx:
        image: loadbalancer
        hostname: nginx
        ports:
            - "80:80"
            - "443:443"
            - "5000:5000"
        depends_on:
            - app_node1
            - app_node2
            - app_node3
volumes:
  redisData:
    external: false
